import React from 'react';
import { motion } from 'framer-motion';
import { MoreVertical, Edit2, Trash2 } from 'lucide-react';

const users = [
  { id: 1, name: 'عمر خالد', email: 'omar@example.com', role: 'مدير نظام', status: 'نشط' },
  { id: 2, name: 'سارة أحمد', email: 'sara@example.com', role: 'محرر', status: 'نشط' },
  { id: 3, name: 'محمد علي', email: 'mohamed@example.com', role: 'مستخدم', status: 'غير نشط' },
  { id: 4, name: 'فاطمة محمود', email: 'fatima@example.com', role: 'مستخدم', status: 'نشط' },
  { id: 5, name: 'ياسر يوسف', email: 'yaser@example.com', role: 'محرر', status: 'معلق' },
];

export const UsersTable: React.FC = () => {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.5 }}
      className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden mt-8"
    >
      <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-white">
        <h3 className="text-lg font-bold text-slate-800">إدارة المستخدمين</h3>
        <button className="bg-primary-600 hover:bg-primary-700 text-white px-4 py-2 rounded-xl text-sm font-medium transition-colors shadow-sm shadow-primary-600/20">
          إضافة مستخدم
        </button>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-right text-sm text-slate-600">
          <thead className="bg-slate-50/80 text-xs uppercase font-semibold text-slate-500 border-b border-slate-100">
            <tr>
              <th scope="col" className="px-6 py-4 rounded-tr-xl">الإسم</th>
              <th scope="col" className="px-6 py-4">البريد الإلكتروني</th>
              <th scope="col" className="px-6 py-4">الدور</th>
              <th scope="col" className="px-6 py-4">الحالة</th>
              <th scope="col" className="px-6 py-4 rounded-tl-xl text-center">الإجراءات</th>
            </tr>
          </thead>
          
          {/* 
            NOTE FOR ANTIGRAVITY BACKEND INTEGRATION:
            The tbody data should be hydrated by calling the endpoints generated by the AntiGravity framework.
            e.g., fetchUsers() -> maps to `.NET 8 MediatR GetUsersQuery` 
          */}
          <tbody className="divide-y divide-slate-100 bg-white">
            {users.map((user) => (
              <tr key={user.id} className="hover:bg-slate-50/50 transition-colors group">
                <td className="px-6 py-4 font-medium text-slate-800 flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-primary-100 text-primary-600 flex items-center justify-center font-bold text-xs uppercase">
                    {user.name.charAt(0)}
                  </div>
                  {user.name}
                </td>
                <td className="px-6 py-4">{user.email}</td>
                <td className="px-6 py-4">
                  <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-slate-100 text-slate-700">
                    {user.role}
                  </span>
                </td>
                <td className="px-6 py-4">
                  <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border
                    ${user.status === 'نشط' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : 
                      user.status === 'معلق' ? 'bg-amber-50 text-amber-700 border-amber-200' : 'bg-slate-100 text-slate-700 border-slate-200'}`}
                  >
                    {user.status === 'نشط' && <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 ml-1.5"></span>}
                    {user.status}
                  </span>
                </td>
                <td className="px-6 py-4 text-center">
                  <div className="flex items-center justify-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button className="p-1.5 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" title="تعديل">
                      <Edit2 className="w-4 h-4" />
                    </button>
                    <button className="p-1.5 text-rose-600 hover:bg-rose-50 rounded-lg transition-colors" title="حذف">
                      <Trash2 className="w-4 h-4" />
                    </button>
                    <button className="p-1.5 text-slate-400 hover:bg-slate-100 rounded-lg transition-colors">
                      <MoreVertical className="w-4 h-4" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="p-4 border-t border-slate-100 bg-slate-50 flex items-center justify-between text-sm text-slate-500">
        <p>عرض 1 إلى 5 من أصل 50 مستخدم</p>
        <div className="flex gap-1">
          <button className="px-3 py-1 rounded border border-slate-200 bg-white hover:bg-slate-50 disabled:opacity-50" disabled>السابق</button>
          <button className="px-3 py-1 rounded border border-slate-200 bg-white hover:bg-slate-50 text-primary-600 font-medium">1</button>
          <button className="px-3 py-1 rounded border border-slate-200 bg-white hover:bg-slate-50">2</button>
          <button className="px-3 py-1 rounded border border-slate-200 bg-white hover:bg-slate-50">التالي</button>
        </div>
      </div>
    </motion.div>
  );
};
